name: Github Actions CI
on: push
jobs:
  build:
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    runs-on: ubuntu-latest
    steps:
    - name: Set up Git repository
      uses: actions/checkout@v2
    - name: Compile LaTeX document
      uses: xu-cheng/latex-action@v2
      with:
        root_file: cv.tex
        latexmk_use_lualatex: true
    - name: Check pdf file
      run: |
        file cv.pdf | grep -q ' PDF '
      if: github.event_name == 'push' && github.ref == 'refs/heads/master'
